apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serverPort }}
      targetPort: {{ .Values.service.serverPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: {{ .Values.service.clientPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-client
